numero1 = int(input("Dame un numero: "))
numero2 = int(input("Dame otro numero: "))
suma=int (numero1+numero2)
resta=int (numero1-numero2)
multiplicacion=int (numero1*numero2)
division=int (numero1//numero2)
print(suma)
print(resta)
print(multiplicacion)
print(division)