numero = int(input("Dame un numero: "))
doble=int (numero*2)
triple=int (numero*3)
cuadrado=int (numero*numero)
print("El doble es:")
print(doble)
print("El triple es:")
print(triple)
print("El cuadrado es:")
print(cuadrado)